USE trivia;
INSERT INTO questions (question, option1, option2, option3, option4, correctAnswer, category)

VALUES ("What is the tallest building in the world as of 2018?", "Shanghai Tower", "Burj Khalifa", "Kingdom Clock Tower", "One World Trade Center", "Burj Khalifa", "Famous Places and Landmarks"),
("The Colosseum is located in which country?", "Italy", "France", "Norway", "Germany", "Italy", "Famous Places and Landmarks"),
("The Great Barrier Reef is located in which country?", "Australia", "China", "Taiwan", "South Africa", "Australia", "Famous Places and Landmarks"),
("In which city is the world's largest medieval cathedral found?", "Paris", "Seville", "Rome", "Athens", "Seville", "Famous Places and Landmarks"),
("Why was the White House painted white?", "White paint was the cheapest.", "Congress voted on it.", "To cover scars after a fire.", "The American people voted on it.", "To cover scars after a fire.", "Famous Places and Landmarks."),
("Where in the Ukraine was there a nuclear explosion in 1986?", "Donetsk", "Kiev", "Odessa", "Chernobyl", "Chernobyl", "80s Trivia"),
("Which volcano in Washington state erupted in 1980?", "Mount Ranier", "Mount St. Helens", "Simcoe", "Glacier Peak", "Mount St. Helens", "80s Trivia"),
("Which spin-off from The Cosby Show premiered in 1987?", "A Different World", "Different Strokes", "Fresh Prince of Bel-Air", "The Facts of Life", "A Different World", "80s Trivia"),
("Which all-girl group had 80s No 1s with Walk Like An Egyptian and Eternal Flame?", "Bananarama", "En Vogue", "The Bangles", "Sister Sledge", "The Bangles", "80s Trivia"),
("In which 80s film did Meryl Streep play a Polish holocaust survivor?", "The French Lieutenant's Woman", "Sophie's Choice", "She-Devil", "Silkwood", "Sophie's Choice", "80s Trivia"),
("Which TV evangelist did George Bush defeat to win the Republican nomination in 1988?", "Pat Robertson", "Billy Graham", "Jimmy Swaggart", "Robert H. Schuller", "Pat Robertson", "80s Trivia"),
("Where were the 1980 Olympics held which were boycotted by American athletes?", "Sarajevo", "Seoul", "Lake Placid", "Moscow", "Moscow", "80s Trivia"),
("In 1989, who had her first of many No 1s with Straight Up?", "Paula Abdul", "Madonna", "Cher", "Tiffany", "Paula Abdul", "80s Trivia"),
("Who attempted to assassinate Ronald Reagan in 1981?", "Mark David Chapman", "John Hinckley Jr", "John Wilkes Booth", "Sirhan Sirhan", "John Hinckley Jr", "80s Trivia"),
("What island was the home of Bob Marley, who died in 1981?", "St. Barts", "Barbados", "Jamaica", "Aruba", "Jamaica", "80s Trivia"),
("Rap was just becoming well known in the 90s. Which artist had the first number one rap single?", "Tupac Shakur", "Coolio", "LL Cool J", "Vanilla Ice", "Vanilla Ice", "90s Trivia"),
("At the 62nd Academy Awards, what film won Best Picture?", "Dead Poet's Society", "Field of Dreams", "Driving Miss Daisy", "My Left Foot", "Driving Miss Daisy", "90s Trivia"),
("In 1990, Iraq invaded what country?", "Syria", "Kuwait", "Saudi Arabia", "Jordan", "Kuwait", "90s Trivia"),
("In what year was The Lion King released?", "1992", "1994", "1993", "1995", "1994", "90s Trivia"),	
("What was O J Simpson driving in the famous police chase?", "Ford Bronco", "Hummer", "Jeep", "Toyota Rav 4", "Ford Bronco", "90s Trivia"),
("What was the name of the rocket that was launched containing Star Trek's Gene Roddenberry's ashes?", "Aethonan", "Pegasus", "Abraxan", "Thestral", "Pegasus", "90s Trivia"),
("Where in the USA was there a total solar eclipse in 1991??", "New Mexico", "Utah", "Hawaii", "California", "Hawaii", "90s Trivia"),
("What element is discovered in 1996?", "Flerovium", "Roentgenium", "Darmstadtium", "Copernicium", "Copernicium", "90s Trivia"),
("The New York Yankees win the 1996 World Series, beating what team 3-2 in game 6 for their first world championship in 18 years?", "Atlanta Braves", "Boston Red Sox", "New York Yankees", "Minnesota Twins", "Atlanta Braves", "90s Trivia"),
("Who did Bill Clinton succeed as the 42nd President of the United States?", "Ronald Reagan", "George H. W. Bush", "George W. Bush", "Gerald Ford", "George H. W. Bush", "90s Trivia"),
("What is the largest country on Earth?", "United States", "China", "Russia", "Austrailia", "Russia", "World Geography"),
("What is the longest river on Earth?", "Amazon River", "Nile River", "Yellow River", "Mississippi River", "Amazon River", "World Geography"),
("What is the highest point above sea level on Earth?", "Mauna Kea", "Mt Everest", "Mt Kilimanjaro", "Andes Mountains", "Mt Everest", "World Geography"),
("What is the largest ocean on Earth?", "Atlantic Ocean", "Artic Ocean", "Pacific Ocean", "Indian Ocean", "Pacific Ocean", "World Geography"),
("What is the largest continent?", "Antarctica", "Asia", "North America", "Africa", "Antarctica", "World Geography"),
("Which Canadian province is the world’s leading exporter of Christmas trees?", "Saskatchewan", "Nova Scotia", "British Columbia", "Quebec", "Nova Scotia", "World Geography"),
("In which country is Timbuktu?", "Nigeria", "Kenya", "Mali", "Tanzania", "Mali", "World Geography"),
("Which is the highest mountain in the Alps?", "Eiger", "Matterhorn", "Weisshorn", "Mont Blanc", "Mont Blanc", "World Geography"),
("Which city’s citizens cross the Bridge of Brotherhood and Unity?", "Sarajevo", "Venice", "Philadelphia", "Vienna", "Sarajevo", "World Geography"),
("The Curragh is in which country?", "Scotland", "Ireland", "England", "Wales", "Ireland", "World Geography"),
("A giraffe's tongue is what color?", "Purple", "Orange", "Black", "Blue", "Black", "Animals"),
("A goat sucker is what type of creature?", "Squirrel", "Fish", "Turtle", "Bird", "Bird", "Animals"),
("What do you call a group of Donkeys?", "Pace", "Army", "Troop", "Chain", "Pace", "Animals"),
("Great Danes come from what European country?", "Denmark", "Germany", "Sweden", "Finland", "Germany", "Animals"),
("What creature can live for the longest period without any water?", "Giraffes", "Camels", "Rats", "Rhinoceros", "Rats", "Animals"),
("What was the name of Dr Dolittle’s Parrot?", "Kiwi", "Baby", "Polly", "Polynesia", "Polynesia", "Animals"),
("A quahog is what type of creature?", "Clam", "Pig", "Butterfly", "Frog", "Clam", "Animals"),
("It is illegal to put what on your bosses desk in Michigan?", "Snake", "Skunk", "Rabbit", "Mouse", "Skunk", "Animals"),
("In an interview,  Walt Disney admitted he was scared of what?", "Ducks", "Dogs", "Mice", "Gerbils", "Mice", "Animals"),
("In the animal kingdom, what creatures are in the order Chiroptera?", "Lizards", "Birds", "Spiders", "Bats", "Bats", "Animals"),
("What superhero  was the first Marvel Comics superhero?", "Human Torch", "Thor", "Spider Man", "Captain Marvel", "Human Torch", "Cartoons"),
("What is Warner Brothers oldest cartoon character?", "Bugs Bunny", "Porky Pig", "Daffy Duck", "Elmer Fudd", "Porky Pig", "Cartoons"),
("Homer Simpson's middle name is what?", "Jerry", "Junkman", "Jay", "Juniper", "Jay", "Cartoons"),
("Originally, what color was Tweety Bird?", "White", "Blue", "Green", "Pink", "Pink", "Cartoons"),
("What comic strip character did Alex Raymond create in 1934?", "Flash Gordon", "Batman", "Superman", "Aquaman", "Flash Gordon", "Cartoons"),
("Before spinach, what did Popeye eat for strength?", "Carrots", "Garlic", "Apples", "Pork Chops", "Garlic", "Cartoons"),
("What is the name of the shrunken city in a bottle in the Superman comics?", "Krypton", "Argo City", "Kandor", "Daxam", "Kandor", "Cartoons"),
("Which comic character was dynamited to death?", "Batgirl", "Kid Flash", "Superboy", "Robin", "Robin", "Cartoons"),
("Walt Disney added what character to Winnie the Pooh that was not in book?", "Gopher", "Kangaroo", "Pig", "Donkey", "Gopher", "Cartoons"),
("What was the first animated film to be nominated for an Oscar for best picture?", "Snow White", "Beauty and the Beast", "101 Dalmatians", "Aladdin", "Beauty and the Beast", "Cartoons"),
("How many inkblots are on the standard Rorschach test?", "8", "12", "10", "6", "10", "Medical"),
("How many miles of arteries, capillaries, and veins are there in the adult human body?", "1,000", "500", "10,000", "62,000", "62,000", "Medical"),
("Who was the first to suggest using contact lenses to improve vision?", "Leonardo da Vinci", "Benjamin Franklin", "Thomas Edison", "Alexander Graham Bell", "Leonardo da Vinci", "Medical"),
("How many of the average adult's 32 permanent teeth are molars?", "8", "12", "4", "6", "12", "Medical"),
("What famous American helped design a germ-proof artificial heart in the early 1930s?", "Andrew Carnegie", "Henry Ford", "Charles Lindbergh", "W.E.B. Du Bois", "Charles Lindbergh", "Medical"),
("What is the average lifespan of a human being's taste bud?", "6 months", "1 month", "2 weeks", "7 to 10 days", "7 to 10 days", "Medical"),
("How many miles of nerves are there in the adult human body?", "45", "25", "35", "50", "45", "Medical"),
("How often does the epidermis, the outer layer of our skin replace itself?", "Once every 6 months", "Once every 4 weeks", "Once every 6 weeks", "Once every 3 months", "Once every 4 weeks", "Medical"),
("How many muscles are there in the human ear?", "12", "9", "6", "16", "6", "Medical"),
("Where on the human face is there a muscle known as the corrugator?", "Chin", "Cheeks", "Nose", "Forehead", "Forehead", "Medical"),
("Which of King Lear's three daughters was murdered?", "Cordelia", "Regan", "Goneril", "Daphne", "Cordelia", "Literature"),
("Whose work 'Parallel Lives' inspired Shakespeare's Roman plays?", "Plato", "Plutarch", "Socrates", "Virgil", "Plutarch", "Literature"),
("Complete the Beatrix Potter book title: 'The Heart of...'?", "Bristol", "Worcestershire", "Gloucester", "Somerset", "Gloucester", "Literature"),
("Which Dickens novel was left unfinished at the time of his death?", "Our Mutual Friend", "Little Dorrit", "Martin Chuzzlewit", "Edwin Drood", "Edwin Drood", "Literature"),
("What was the name of the Onondaga chief about whom Longfellow wrote and epic poem?", "Hiawatha", "Geronimo", "Tadodaho", "Jigonhsasee", "Hiawatha", "Literature"),
("Who wrote Boris Godunov?", "Dostoyevsky", "Pushkin", "Tolstoy", "Chekhov", "Pushkin", "Literature"),
("Which French author, the son of one of Napoleon's generals, spent 19 years exiled in Guernsey?", "Proust", "Flaubert", "Hugo", "Balzac", "Hugo", "Literature"),
("Who wrote 'Of Human Bondage'?", "Faulkner", "Steinbeck", "Hemingway", "Maugham", "Maugham", "Literature"),
("Which English writer married Anne Hathaway?", "Shakespeare", "Woodsworth", "Chaucer", "Marlowe", "Shakespeare", "Literature"),
("Which was the home planet for the aliens in H. G. Wells' 'War of the Worlds'?", "Venus", "Mars", "Mercury", "Pluto", "Mars", "Literature"),
("In Michigan it is illegal to chain what to a fire hydrant?", "A cat", "A lizard", "An alligator", "A bicycle", "An alligator", "Funny"),
("What did people in the Middle Ages throw at the bride and groom?", "Pasta", "Mushrooms", "Fennel seeds", "Eggs", "Eggs", "Funny"),	
("33% of the world's population can't do what?", "Snap their fingers.", "Click their tongues.", "Cross their eyes.", "Sing on pitch.", "Snap their fingers.", "Funny"),
("In Massachusetts, what is illegal to have in the bathroom?", "A hair dryer", "A light switch", "A toilet", "An electric toothbrush", "A light switch", "Funny"),
("In Texas, it's illegal to swear in front of a...?", "priest", "woman", "corpse", "child", "corpse", "Funny"),
("In Minnesota, it is illegal to tease what type of animal?", "rabbit", "raccoon", "bear", "skunk", "skunk", "Funny"),
("Over a lifetime, the average person grows how much nose hair?", "7 feet", "10 feet", "3 feet", "1 mile", "7 feet", "Funny"),
("The world's busiest MacDonald's is located in what city?", "Beijing", "Moscow", "Tokyo", "Pyongyang", "Moscow", "Funny"),
("14% of Americans could not identify which country on a map?", "Canada", "Mexico", "America", "Russia", "America", "Funny"),
("What soft drink should you be served if you ask for a Shoot Me a Waco?", "7-Up", "Root Beer", "Sarsaparilla", "Dr. Pepper", "Dr. Pepper", "Funny"),
("In which film did Cher win an Oscar playing Loretta Castorini?", "Moonstruck", "Mask", "Mermaids", "Silkwood", "Moonstruck", "The Oscars"),
("In which decade of the 20th century were the Oscars born?", "30s", "20s", "40s", "50s", "20s", "The Oscars"),
("For which film did Robert de Niro win his first Oscar?", "The Godfather", "Taxi Driver", "The Godfather Part II", "Raging Bull", "The Godfather Part II", "The Oscars"),
("Whose 1989 Oscar for 'Glory' was the first awarded to a black American in 50 years?", "Morgan Freeman", "Andre Braugher", "Raymond St. Jacques", "Denzel Washington", "Denzel Washington", "The Oscars"),
("The movie 'Titanic' won 11 Oscars but for how many was it nominated?", "14", "18", "16", "12", "14", "The Oscars"),
("In 1973, what movie became the first horror film ever to be nominated for Best Film Oscar?", "Jaws", "The Exorcist", "Carrie", "The Omen", "The Exorcist", "The Oscars"),
("Meryl Streep co-starred with which Oscar-winning actor in Kramer vs Kramer in 1979?", "Jack Nicholson", "Richard Dreyfuss", "Dustin Hoffman", "Christopher Walken", "Dustin Hoffman", "The Oscars"),
("For what movie did the Beatles win their one and only Oscar?", "A Hard Day's Night", "Yellow Submarine", "Help!", "Let It Be", "Let It Be", "The Oscars"),
("What remake of a long-running TV show was the only remake to get a Best Picture nomination?", "The Fugitive", "The Untouchables", "Mission: Impossible", "Dragnet", "The Fugitive", "The Oscars"),
("Who was the first African-American to win an Oscar?", "Diana Ross", "Hattie McDaniel", "Sidney Poitier", "Isaac Hayes", "Hattie McDaniel", "The Oscars"),
("On what vegetable did an ancient Egyptian place his right hand when taking an oath?", "carrot", "turnip", "onion", "corn", "onion", "Food"),
("How many flowers are in the design stamped on each side of an Oreo cookie?", "1", "2", "4", "12", "12", "Food"),
("What European nation consumes more spicy Mexican food than any other?", "Norway", "Spain", "Italy", "Germany", "Norway", "Food"),
("What is the two top selling spice in the world?", "Mustard", "Pepper", "Salt", "Cinnamon", "Pepper", "Food"),
("What is the most widely eaten fish in the world?", "Cod", "Salmon", "Herring", "Sardine", "Herring", "Food"),
("The milk of what animal is used to make authentic Italian mozzarella cheese?", "cow", "goat", "sheep", "water buffalo", "water buffalo", "Food"),
("What was the first commercially manufactured breakfast cereal?", "Shredded Wheat", "Corn Flakes", "Muesli", "Cheerios", "Shredded Wheat", "Food"),
("What American city produces most of the egg rolls sold in grocery stores in the United States?", "San Fransisco, CA", "Houston, TX", "Boston, MA", "Fort Myers, FL", "Houston, TX", "Food"),
("What was the first of H.J. Heinz' '57 varieties'?", "Mustard", "Ketchup", "Horseradish", "Vinegar", "Horseradish", "Food"),
("What hit the market alongside spinach as the first frozen veggies?", "Carrots", "Green Beans", "Corn", "Peas", "Peas", "Food");

INSERT INTO leaderboards (name, score)
VALUES ('Jim', 5),
('Jimmy', 4),
('Jimmerson', 3),
('James', 2);
SELECT * FROM questions;